---
author: Jad Toghuj
description: Jad Toghuj | Editorial Stylist | Creative Director | Amman, Jordan
email: jadtoghuj@gmail.com
instagram: "@jad.toghuj"
footer_text: |-
  <span>Â© 2021 <a href="https://instagram.com/jad.toghuj" title="Jad Toghuj on Instagram" target="_blank">Jad Toghuj</a></span>
  <span style="margin: 0;">Editorial Stylist | Creative Director</span>
  <span style="margin: 0;">All rights reserved</span>
  <span>Website by <a href="https://basharalidreesi.com" title="Bashar al-Idreesi" target="_blank">Basabees</a></span>
